language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
- npm install -g jasmine-core
script:
- npm test
notifications:
  slack:
    secure: sbZXnqNYjzn1I93nNkMtt6OZJQGBcM81/u9+/mjk/OA3aU/tpdp4ByXJ6mDBOqjEoEx0UDd/jPeml6iyjNzUHAJiBeQJdXD6tTqbxbknR4aOnftUr5EwtRLFMWUbi3fSqq6iOuGC5HR4jiIVTzDPtHqsTxWjVlkKbdEMFG42x8CsmjzcqbE632dtfwOQOxUVSzWfOkQ7+EYHpakJYI/9ehnTQSp1wM2nKEJUpb6pbwNajuNApPlSwsPSsD5VnRwLwL2SoQ0aeZnniLqiVGTJCNkj+UjaPMLBQ2toyaY/cT2NdrvqgKbJ3ZnJglulk6JSHNhMhzmXjZrN4Q91UfTtIY5okbUZttms59DI+QNVL+G4d6iLWhSU9Qhhg/XLrUoI713lVGWsBdEZzINwmKGmc9zk8wYGIid843V1HHgXnG9qWbVt5Ma0pw6vrlTIS+roEA5EKOb/ENqrVZpX3JYfA+CA+FEuHPuHWwiZiUf3XR+SpPGUo34yYPbvEvCSKXTwWMWp7ln2xY8AJ3PLa5MzjTxOCVD30Oy6O+Hp3Rl8Z3EmdPpz6pZAiXpx554itBFsUt4h1tP0ggO4DLWepBZwqqrFumkh9xWgXO9kbrqyiC1/iIOLp5CvVdAj0WSAIut1O4qpE21PZBx+9bLA9lDWAKwTQQn6Buxwh0BUaNL5VOY=
